### ISSUE TITLE
[Not issue] How is your port working?

### ISSUE THREAD

**Issue by 0312birdzhang** [M0Rf30/halium_manifest_xiaomi_vince#1]
Hi M0Rf30, i'm porting halium9 to vince too, and still can't get GUI, android not mounted well, logs: https://pastebin.com/RbZ8TSjn
, is your port GUI working?

BTW, we have an organization https://github.com/ubports-on-vince and a telegram group https://t.me/vincehalium.

**Comment by M0Rf30** [comment]
Hi @0312birdzhang I know of your attempt, I've seen your first trials in the telegram group without joining it and the unofficial ubport. For now the work on halium is suspended cause I'm very busy and vince is my current running device. BTW my first priority is an updated and working postmarketOS for vince. So here comes halium, in order to accomplish a running pmOS instance. But I've just built an image for vince without deep diving. As concerning your log I don't know what to say: fs problems of course at a first glance.

**Comment by 0312birdzhang** [comment]
Okay, waiting for you to have some time continue porting, thanks for your postmarketOS work.
